### PR TITLE
Fix ci linting

### PR DESCRIPTION
**Pull request by gardar**
Fixes ansible-lint versions 5+ failing to find ansible role.

Related: https://github.com/ansible/ansible-lint/issues/1329

As well as removing deprecated mergify strict mode https://blog.mergify.com/strict-mode-deprecation/

### CODE REVIEW

**Comment by gardar** [comment]
This should perhaps be applied from the [skeleton](https://github.com/cloudalchemy/skeleton) instead. I've created a PR there as well https://github.com/cloudalchemy/skeleton/pull/13

Although it's unclear if this repo is being synced from the skeleton, leaving this PR open in case it's not.

**Comment by SuperQ** [comment]
Yes, we do sync some of these configs from skeleton.

**Comment by gardar** [comment]
That's a good idea! I first noticed the issue here and I wasn't aware of the skeleton, and then once I came across the skeleton it wasn't perfectly clear where it's being used

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**

**Pull request closed without merging**
