### PR TITLE
Some "false" were incorrectly substituted to "no"

### PR DESCRIPTION
**Pull request by wzyboy**
This PR fixes them.

### CODE REVIEW

**Comment by paulfantom** [comment]
thanks! :+1:

**Comment by dmke** [comment]
Uhm... @paulfantom could you have a look at the diff again?

```diff
+  # run_once: true # <-- this canfalset be set due to multi-arch support
-  # run_once: true # <-- this cannot be set due to multi-arch support
```

```diff
+ # - name: change pam falsefile limits for prometheus
- # - name: change pam nofile limits for prometheus
```

```diff
+ #     limit_item: falsefile
- #     limit_item: nofile
```

**Comment by paulfantom** [comment]
I think you did diff in the opposite way :) This PR is properly fixing incorrect substitution.

**Comment by dmke** [comment]
Indeed. I need (more) coffee. :grinning: 

Sorry for the noise.

**Pull request merged**
