### PR TITLE
Add management of basic auth password files

### PR DESCRIPTION
**Pull request by escalate**

### CODE REVIEW

**Comment by paulfantom** [comment]
I don't see any integration point of this feature with already existing features in this role. Why this should be in the role and not defined on a playbook level?

**Comment by escalate** [comment]
Hello @paulfantom 

My requirements are that I do not have to encrypt the configuration for Prometheus completely. Currently I would have to move the complete content of the variable "prometheus_scrape_configs" into the Ansible Vault to encrypt the Basic Auth password variable. I think this is the wrong approach. I want to leave the variable "prometheus_scrape_configs" unencrypted and only encrypt passwords.
But this is not possible using the Ansible encrypted variable method. I always get an error when running Ansible.

`- job_name: node-exporter
    scheme: https
    basic_auth:
      username: node-exporter
      password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
...`

Via the detour of the password file I can simply move the variable "prometheus_basic_auth_password_files" completely into Ansible Vault. Only the path to the password files must be stored in the variable "prometheus_scrape_configs". 

`- job_name: node-exporter
    scheme: https
    basic_auth:
      username: node-exporter
      password_file: "{{ prometheus_config_dir }}/.node-exporter.pass"`

From a technical point of view, I could of course outsource this code, e.g. into a separate role or as a Playbook task.

But I see this as an inconsistent way. I would like to use the prometheus_ variable scope. But this role is already responsible for this. Using the variable scope in another scope would possibly cause problems. I would like to prevent this.

Furthermore it is an official possibility of Prometheus and should belong to a feature complete role in my opinion.

Greetings from Berlin
Felix

**Comment by paulfantom** [comment]
As I see it there are 2 issues:

1) > I want to leave the variable "prometheus_scrape_configs" unencrypted and only encrypt passwords. But this is not possible using the Ansible encrypted variable method.

This **should** be possible. Maybe like this:

```
prom_node_password: !vault | $ANSIBLE_VAULT;1.1;AES256 ...
prometheus_scrape_configs:
- job_name: "node"
  scheme: https
  basic_auth:
    username: node-exporter
    password: "{{ prom_password }}"
  static_configs:
  - targets:
    - "some_url:9100"
```

2) [This role doesn't look at any scrape config](https://github.com/cloudalchemy/ansible-prometheus/blob/master/templates/prometheus.yml.j2#L33-L34) and this is on purpose to be future proof and support whatever prometheus is supporting. Adding `prometheus_basic_auth_password_files` breaks this as we would need to add preflight checks to find out if those files are used or not (preventing users from breaking their own stuff).

---

I am mostly worried that when/if prometheus adds support for certificate auth in scrape_config, this role would need to support copying and managing certs, because it was already supporting the same for basic auth password files.

**Comment by escalate** [comment]
Thanks for your help. The workaround with the variables works for me. I will close this PR and delete my fork.

**Pull request closed without merging**
