### PR TITLE
Separate downloading and unpacking prometheus archive

### LINKED ISSUE #101: Can't download release due to Github redirect the request
From an unknown time, Github starts to redirect download request to AWS s3. And since using ansible `unarchive` module with `remote_src` won't follow the redirect URL, the task will actually download an HTML and report some __tar__ error like this:

```
fatal: [test -> localhost]: FAILED! => {"attempts": 1, "changed": false, "msg": "Failed to find handler for \"/private/var/folders/5m/1f26j_6d3jnbp4y30g8rhlgc0000gn/T/ansible_CxcU89/prometheus-2.2.1.linux-amd64.tar.gz\". Make sure the required command to extract the file is installed. Command \"/usr/bin/tar\" detected as tar type bsd. GNU tar required. Command \"/usr/bin/unzip\" could not handle archive."}
```

My two cents on this, and according to the discussion from https://github.com/ansible/ansible/issues/19985#issuecomment-270999632, might be split the download and unarchive into two tasks. It will be even greater if we can extract download src as an overwritable variable.

### PR DESCRIPTION
**Pull request by paulfantom**
Resolves #101 

Possibly accidentally solves ans issue with too many downloads of prometheus archive to localhost.

### CODE REVIEW

**Comment by taiansu** [comment]
Thanks for the blasting fast fixing. I tried the fix, and with two minor modifications, it works correctly. 

The changes are:
  1. Replace line#55 's `delegate_to: localhost` with `remote_src: yes`
  2. Add a `remote_src: yes` for `copy` module, for example, between line#61 and line#62.

**Comment by SuperQ** [comment]
Thinking about this, can we download these archives to something like `/opt/prometheus/.archive/` rather than `/tmp`?  I'm not sure if the ansible `get_url` is safe against existing symlinks/hardlinks in `/tmp`.

**Comment by paulfantom** [comment]
@taiansu your modifications would change how we want this role to work. If we add `remote_src` in the places you say it will cause ansible to download archives to target hosts and this is highly inefficient in large infrastructures (also sometimes won't work if target hosts doesn't have internet access).
Our approach is to download archives from internet to deployer machine (one which runs ansible) and propaagte from this machine to other nodes.

**Comment by paulfantom** [comment]
@SuperQ we could probably use `tmp_dest` of `get_url` module to solve this issue, but I need to look closer at it.

**Comment by paulfantom** [comment]
@taiansu can you tell what is not working in current version? Some error messages could be useful.

**Comment by SuperQ** [comment]
One other nice thing, it would be good to cache this so it doesn't download the file every time.  In theory, we could extract the checksum from the sums published on github.

**Comment by paulfantom** [comment]
@SuperQ I agree that it would be nice to validate checksums. This option is even provided in `get_url` module. However first we would need to download checksums. I think it would be better to split it into another issue (#104).
As for caching, this won't be possible with `tmp_dest` parameter and I don't think that storing it in `/opt` is a good idea. Currently we provide some caching functionality by storing files in `/tmp` directory, which is cleaned only after deployer machine is rebooted.

**Comment by taiansu** [comment]
Yes I understand that will change the behaviour. If I apply the changes as is, the first error I got is like:

```
fatal: [test -> localhost]: FAILED! => {"changed": false, "msg": "Failed to get information on remote file (/tmp): sudo: a password is required\n"}
```

And adding `become: yes` to the unarchive module still got the same error.

**Comment by paulfantom** [comment]
@taiansu this should be fixed now, could you test it?

**Comment by paulfantom** [comment]
@SuperQ I don't think we can use other directories on deployer machine apart from `/tmp` due to permission issues.

**Comment by rdemachkovych** [comment]
For me, it's required install libselinux-python and work fine

**Comment by taiansu** [comment]
I tried the fix, but I got the simillar error back to the first point:
```
fatal: [test -> localhost]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/Users/tai/.ansible/tmp/ansible-tmp-1524074379.55-78415089495321/source\". Make sure the required command to extract the file is installed. Command \"/usr/bin/tar\" detected as tar type bsd. GNU tar required. Command \"/usr/bin/unzip\" could not handle archive."}
```

So I'm wondering the error may not be relate to the separate the download and unarchve, but rather we just can't unarchive a linux tart in the host while it's a Mac.

Anyway thanks for all the help.

**Comment by paulfantom** [comment]
@taiansu yes it seems that there is a problem with `tar` on Mac:

> Make sure the required command to extract the file is installed. Command \"/usr/bin/tar\" detected as tar type bsd. GNU tar required. Command \"/usr/bin/unzip\" could not handle archive.

Could you check if after installing `gnu-tar` this works?
```
brew install gnu-tar
```

**Comment by paulfantom** [comment]
Great!
I've added this to readme in requirements section.

**Comment by rdemachkovych** [comment]
Should we also update the [Requiremets](https://github.com/cloudalchemy/ansible-prometheus#requirements) in the README?

**Pull request merged**
