### PR TITLE
New prometheus/prometheus upstream release!

### PR DESCRIPTION
**Pull request by cloudalchemybot**
Devs at [prometheus/prometheus](https://github.com/prometheus/prometheus) released new software version - **2.20.1**! This PR updates code to bring new version into repository.

This is an automated PR, if you don't want to receive those, please contact @paulfantom.

## Commit Message
create [patch] release

### CODE REVIEW

**Comment by roidelapluie** [comment]
mmh 2.21, 2.19.3 has been released and this PR is failing (but still points to 2.20)

**Comment by paulfantom** [comment]
It's failing due to issues not related to the PR. Let's close this and allow bot to open new PR with 2.21 version.

**Comment by roidelapluie** [comment]
Should the bot force push the branch?

**Comment by paulfantom** [comment]
Ideally yes and it is on my long TODO list. It's just I don't have time to implement it now :(

If you want to tackle this, here is a script which is used for those updates: https://github.com/cloudalchemy/auto-maintenance/blob/master/autocommiter.sh

**Pull request closed without merging**
