### PR TITLE
Remove unnecessary dependency on jmespath

### PR DESCRIPTION
**Pull request by flowerysong**
This is fairly straightforward manipulation to do with standard Jinja features, there's no need to use a non-default library.

### CODE REVIEW

**Comment by SuperQ** [comment]
This needs a rebase to get the tests to pass.

**Comment by SuperQ** [comment]
Or, maybe something else is broken. :frowning_face:

**Comment by SuperQ** [comment]
Ahh, I think I see what's going on. `molecule` is not creating the role symlink because it's a PR from a fork. Boo.

**Comment by sdarwin** [comment]
> Or, maybe something else is broken.

This is a brief window of time during which the latest newest ansible-compat is broken.  
Change test-requirements.txt:

```
# temporarily lock versions of molecule and ansible-compat to avoid a bug:
ansible-compat==0.5.0
molecule==3.5.2
```

**Comment by SuperQ** [comment]
Ok, fixed HEAD. Please rebase again.

**Comment by flowerysong** [comment]
@SuperQ Looking a little better, but it's still complaining about the Mergify configuration, and I'm not sure what's up with the failure for test-2.9-default.

**Comment by sdarwin** [comment]
- mergify strict mode is end-of-life
- circleci config file, should run on large instances.  resource_class: large

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**

**Pull request closed without merging**
