### PR TITLE
auto set go architecture

### PR DESCRIPTION
**Pull request by paulfantom**
This will allow to use this role on platforms different than x86_64.

### CODE REVIEW

**Comment by SuperQ** [comment]
I was thinking about doing something like this, but with a dictionary lookup.

vars/main.yml
```yaml
ansible_to_go_arch:
  x86_64: amd64
  aarch64: arm64
  armv7l: arm7
```

Then you can do:
```yaml
set_fact:
  go_arch: "{{ ansible_to_go_arch[ansible_architecture] }}"
```

**Comment by paulfantom** [comment]
Oh, nice!
We can probably even get rid of `set_fact` by using this:
```
"{{ ansible_to_go_arch[ansible_architecture] | default(ansible_architecture) }}"
```

**Comment by SuperQ** [comment]
LGTM, I just made the [same change](https://gitlab.com/superq/prometheus-ansible/commit/d3801a9790adc0ddaaba39c612ed853d56c92f19).

**Comment by paulfantom** [comment]
I've propagated this change to other roles. However all this PRs will need to wait for @rdemachkovych reviews and he's currently on vacation.

**Pull request merged**
