### PR TITLE
Allow to override the default prometheus.service.j2 template

### PR DESCRIPTION
**Pull request by m12o**

### CODE REVIEW

**Comment by paulfantom** [comment]
What is the purpose of this? What problem does it solve?

**Comment by m12o** [comment]
Nneed to replace the provided systemd unit file with our custom file

**Comment by SuperQ** [comment]
There are better ways to override the unit file using systemd. For example [drop-in units](https://coreos.com/os/docs/latest/using-systemd-drop-in-units.html) can be used to override any part of the main unit template.

**Comment by paulfantom** [comment]
As @SuperQ suggested, systemd options can be overridden by using systemd-native features without unnecessary complicating ansible role. You can provide additional files on playbook level.

**Pull request closed without merging**
