### PR TITLE
Deploy console templates

### PR DESCRIPTION
**Pull request by SuperQ**
Include the default Prometheus console templates.

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by paulfantom** [comment]
@SuperQ Could you add tests in https://github.com/cloudalchemy/ansible-prometheus/blob/master/molecule/default/tests/test_default.py for checking if those files are present?

**Comment by SuperQ** [comment]
@paulfantom Done.

**Comment by paulfantom** [comment]
@SuperQ merge when you want to :+1:

**Comment by SuperQ** [comment]
It looks like I don't have merge permission.

**Comment by paulfantom** [comment]
This should be fixed by now. Are you able to merge?

**Pull request merged**
